const verbData = [
  {
    prefix: "",
    sentences: [
      { english: "I went (male, on foot)", russian: "я шёл" },
      { english: "I went (female, on foot)", russian: "я шла" },
      { english: "he went (on foot)", russian: "он шёл" },
      { english: "she went (on foot)", russian: "она шла" },
      { english: "we went (on foot)", russian: "мы шли" },
      { english: "you went (on foot)", russian: "вы шли" },
      { english: "they went (on foot)", russian: "они шли" },
      { english: "I was going (on foot)", russian: "я ходил" },
      { english: "he was going (on foot)", russian: "он ходил" },
      { english: "she was going (on foot)", russian: "она ходила" },
      { english: "we were going (on foot)", russian: "мы ходили" },
      { english: "they were going (on foot)", russian: "они ходили" },
      { english: "I went (male, by vehicle)", russian: "я ехал" },
      { english: "I went (female, by vehicle)", russian: "я ехала" },
      { english: "he went (by vehicle)", russian: "он ехал" },
      { english: "she went (by vehicle)", russian: "она ехала" },
      { english: "we went (by vehicle)", russian: "мы ехали" },
      { english: "they went (by vehicle)", russian: "они ехали" },
      { english: "I was going (by vehicle)", russian: "я ездил" },
      { english: "she was going (by vehicle)", russian: "она ездила" },
      { english: "we were going (by vehicle)", russian: "мы ездили" },
      { english: "they were going (by vehicle)", russian: "они ездили" }
    ]
  },
  {
    prefix: "у",
    sentences: [
      { english: "I left (male, on foot)", russian: "я ушёл" },
      { english: "I left (female, on foot)", russian: "я ушла" },
      { english: "he left (on foot)", russian: "он ушёл" },
      { english: "she left (on foot)", russian: "она ушла" },
      { english: "they left (on foot)", russian: "они ушли" },
      { english: "I left (male, by vehicle)", russian: "я уехал" },
      { english: "I left (female, by vehicle)", russian: "я уехала" },
      { english: "he left (by vehicle)", russian: "он уехал" },
      { english: "she left (by vehicle)", russian: "она уехала" },
      { english: "they left (by vehicle)", russian: "они уехали" },
      { english: "we left (on foot)", russian: "мы ушли" },
      { english: "we left (by vehicle)", russian: "мы уехали" },
      { english: "you left (on foot)", russian: "вы ушли" },
      { english: "you left (by vehicle)", russian: "вы уехали" },
      { english: "he had left (on foot)", russian: "он уже ушёл" },
      { english: "she had left (by vehicle)", russian: "она уже уехала" },
      { english: "they suddenly left (on foot)", russian: "они внезапно ушли" },
      { english: "we quietly left (by vehicle)", russian: "мы тихо уехали" },
      { english: "I left the meeting (on foot)", russian: "я ушёл с собрания" },
      { english: "he left school (by vehicle)", russian: "он уехал из школы" },
      { english: "they left for Moscow", russian: "они уехали в Москву" },
      { english: "she left home early", russian: "она рано ушла из дома" }
    ]
  },
  {
    prefix: "при",
    sentences: [
      { english: "I arrived (male, on foot)", russian: "я пришёл" },
      { english: "I arrived (female, on foot)", russian: "я пришла" },
      { english: "he arrived (on foot)", russian: "он пришёл" },
      { english: "she arrived (on foot)", russian: "она пришла" },
      { english: "they arrived (on foot)", russian: "они пришли" },
      { english: "we arrived (on foot)", russian: "мы пришли" },
      { english: "I arrived (male, by vehicle)", russian: "я приехал" },
      { english: "I arrived (female, by vehicle)", russian: "я приехала" },
      { english: "he arrived (by vehicle)", russian: "он приехал" },
      { english: "she arrived (by vehicle)", russian: "она приехала" },
      { english: "they arrived (by vehicle)", russian: "они приехали" },
      { english: "we arrived (by vehicle)", russian: "мы приехали" },
      { english: "he just arrived (on foot)", russian: "он только что пришёл" },
      { english: "she just arrived (by vehicle)", russian: "она только что приехала" },
      { english: "they arrived from work (on foot)", russian: "они пришли с работы" },
      { english: "I arrived at school (by vehicle)", russian: "я приехал в школу" },
      { english: "she arrived late (on foot)", russian: "она опоздала и пришла позже" },
      { english: "we arrived early (by vehicle)", russian: "мы приехали рано" },
      { english: "they arrived on time (on foot)", russian: "они пришли вовремя" },
      { english: "you arrived together (by vehicle)", russian: "вы приехали вместе" },
      { english: "he arrived at the station", russian: "он приехал на вокзал" },
      { english: "I arrived at the party", russian: "я пришёл на вечеринку" }
    ]
  },
  {
    prefix: "по",
    sentences: [
      { english: "I started walking (male)", russian: "я пошёл" },
      { english: "I started walking (female)", russian: "я пошла" },
      { english: "he started walking", russian: "он пошёл" },
      { english: "she started walking", russian: "она пошла" },
      { english: "they started walking", russian: "они пошли" },
      { english: "I started driving (male)", russian: "я поехал" },
      { english: "I started driving (female)", russian: "я поехала" },
      { english: "he started driving", russian: "он поехал" },
      { english: "she started driving", russian: "она поехала" },
      { english: "they started driving", russian: "они поехали" },
      { english: "we started walking", russian: "мы пошли" },
      { english: "we started driving", russian: "мы поехали" },
      { english: "he went off to the store", russian: "он пошёл в магазин" },
      { english: "she went off to class", russian: "она пошла на занятия" },
      { english: "they went out for a walk", russian: "они пошли гулять" },
      { english: "I headed home", russian: "я пошёл домой" },
      { english: "we went to the countryside", russian: "мы поехали за город" },
      { english: "they drove to work", russian: "они поехали на работу" },
      { english: "she left for school", russian: "она поехала в школу" },
      { english: "you started walking (plural)", russian: "вы пошли" },
      { english: "you started driving (plural)", russian: "вы поехали" },
      { english: "he went to the theater", russian: "он поехал в театр" }
    ]
  },
  {
    prefix: "в",
    sentences: [
      { english: "I went in (male, on foot)", russian: "я вошёл" },
      { english: "I went in (female, on foot)", russian: "я вошла" },
      { english: "he went in (on foot)", russian: "он вошёл" },
      { english: "she went in (on foot)", russian: "она вошла" },
      { english: "we went in (on foot)", russian: "мы вошли" },
      { english: "they went in (on foot)", russian: "они вошли" },
      { english: "I entered (by vehicle)", russian: "я въехал" },
      { english: "she entered (by vehicle)", russian: "она въехала" },
      { english: "he entered (by vehicle)", russian: "он въехал" },
      { english: "we entered (by vehicle)", russian: "мы въехали" },
      { english: "they entered (by vehicle)", russian: "они въехали" },
      { english: "I used to go in (on foot)", russian: "я входил" },
      { english: "she used to go in (on foot)", russian: "она входила" },
      { english: "they used to go in (on foot)", russian: "они входили" },
      { english: "we used to go in (on foot)", russian: "мы входили" },
      { english: "he used to go in (by vehicle)", russian: "он въезжал" },
      { english: "we used to enter (by vehicle)", russian: "мы въезжали" },
      { english: "they used to go in (by vehicle)", russian: "они въезжали" },
      { english: "I entered the house (on foot)", russian: "я вошёл в дом" },
      { english: "she entered the room (on foot)", russian: "она вошла в комнату" },
      { english: "he drove into the yard", russian: "он въехал во двор" },
      { english: "they went into the building (on foot)", russian: "они вошли в здание" }
    ]
  },
  {
    prefix: "вы",
    sentences: [
      { english: "I went out (male, on foot)", russian: "я вышел" },
      { english: "I went out (female, on foot)", russian: "я вышла" },
      { english: "he went out (on foot)", russian: "он вышел" },
      { english: "she went out (on foot)", russian: "она вышла" },
      { english: "we went out (on foot)", russian: "мы вышли" },
      { english: "they went out (on foot)", russian: "они вышли" },
      { english: "you (formal) went out (on foot)", russian: "вы вышли" },
      { english: "I exited (by vehicle)", russian: "я выехал" },
      { english: "she exited (by vehicle)", russian: "она выехала" },
      { english: "he exited (by vehicle)", russian: "он выехал" },
      { english: "we exited (by vehicle)", russian: "мы выехали" },
      { english: "they exited (by vehicle)", russian: "они выехали" },
      { english: "I used to go out (on foot)", russian: "я выходил" },
      { english: "she used to go out (on foot)", russian: "она выходила" },
      { english: "they used to go out (on foot)", russian: "они выходили" },
      { english: "we used to go out (on foot)", russian: "мы выходили" },
      { english: "he used to exit (by vehicle)", russian: "он выезжал" },
      { english: "we used to exit (by vehicle)", russian: "мы выезжали" },
      { english: "they used to exit (by vehicle)", russian: "они выезжали" },
      { english: "she stepped out of the room", russian: "она вышла из комнаты" },
      { english: "he drove out of the garage", russian: "он выехал из гаража" },
      { english: "they came out of the house", russian: "они вышли из дома" }
    ]
  },
  {
    prefix: "до",
    sentences: [
      { english: "I reached (male, on foot)", russian: "я дошёл" },
      { english: "I reached (female, on foot)", russian: "я дошла" },
      { english: "he reached (on foot)", russian: "он дошёл" },
      { english: "she reached (on foot)", russian: "она дошла" },
      { english: "we reached (on foot)", russian: "мы дошли" },
      { english: "they reached (on foot)", russian: "они дошли" },
      { english: "you (formal) reached (on foot)", russian: "вы дошли" },
      { english: "I reached (by vehicle)", russian: "я доехал" },
      { english: "she reached (by vehicle)", russian: "она доехала" },
      { english: "he reached (by vehicle)", russian: "он доехал" },
      { english: "we reached (by vehicle)", russian: "мы доехали" },
      { english: "they reached (by vehicle)", russian: "они доехали" },
      { english: "I used to reach (on foot)", russian: "я доходил" },
      { english: "she used to reach (on foot)", russian: "она доходила" },
      { english: "they used to reach (on foot)", russian: "они доходили" },
      { english: "we used to reach (on foot)", russian: "мы доходили" },
      { english: "he used to reach (by vehicle)", russian: "он доезжал" },
      { english: "we used to reach (by vehicle)", russian: "мы доезжали" },
      { english: "they used to reach (by vehicle)", russian: "они доезжали" },
      { english: "he reached the end of the street", russian: "он дошёл до конца улицы" },
      { english: "they drove all the way to Moscow", russian: "они доехали до Москвы" },
      { english: "she reached the library", russian: "она дошла до библиотеки" }
    ]
  },
  {
    prefix: "за",
    sentences: [
      { english: "I dropped in (male, on foot)", russian: "я зашёл" },
      { english: "I dropped in (female, on foot)", russian: "я зашла" },
      { english: "he dropped in (on foot)", russian: "он зашёл" },
      { english: "she dropped in (on foot)", russian: "она зашла" },
      { english: "we dropped in (on foot)", russian: "мы зашли" },
      { english: "they dropped in (on foot)", russian: "они зашли" },
      { english: "you (formal) dropped in (on foot)", russian: "вы зашли" },
      { english: "I stopped by (by vehicle)", russian: "я заехал" },
      { english: "she stopped by (by vehicle)", russian: "она заехала" },
      { english: "they stopped by (by vehicle)", russian: "они заехали" },
      { english: "we stopped by (by vehicle)", russian: "мы заехали" },
      { english: "he went behind the building (on foot)", russian: "он зашёл за здание" },
      { english: "she entered the room", russian: "она зашла в комнату" },
      { english: "they came in for a minute", russian: "они зашли на минутку" },
      { english: "we used to stop by often (on foot)", russian: "мы заходили часто" },
      { english: "he used to drop in (on foot)", russian: "он заходил" },
      { english: "they used to stop by (by vehicle)", russian: "они заезжали" },
      { english: "she used to drop in (on foot)", russian: "она заходила" },
      { english: "I used to stop by (by vehicle)", russian: "я заезжал" },
      { english: "he drove behind the building", russian: "он заехал за здание" },
      { english: "they went in for coffee", russian: "они зашли за кофе" },
      { english: "he popped in to say hello", russian: "он зашёл поздороваться" }
    ]
  },
  {
    prefix: "про",
    sentences: [
      { english: "I passed by the school (on foot)", russian: "я прошёл мимо школы" },
      { english: "She passed by the shop (on foot)", russian: "она прошла мимо магазина" },
      { english: "We passed the cathedral (on foot)", russian: "мы прошли мимо собора" },
      { english: "They passed by quickly (on foot)", russian: "они быстро прошли мимо" },
      { english: "He walked through the forest", russian: "он прошёл через лес" },
      { english: "She walked through the gate", russian: "она прошла через ворота" },
      { english: "I passed the exam (figuratively)", russian: "я прошёл экзамен" },
      { english: "She passed her driver's test", russian: "она прошла экзамен по вождению" },
      { english: "We walked a long distance", russian: "мы прошли большое расстояние" },
      { english: "They went through all the documents", russian: "они прошли все документы" },
      { english: "I drove through the tunnel", russian: "я проехал через туннель" },
      { english: "She drove through the city", russian: "она проехала через город" },
      { english: "He drove past the station", russian: "он проехал мимо станции" },
      { english: "We passed several villages", russian: "мы проехали несколько деревень" },
      { english: "They drove a thousand kilometers", russian: "они проехали тысячу километров" },
      { english: "I drove through customs", russian: "я проехал таможню" },
      { english: "She passed by without noticing", russian: "она прошла мимо, не заметив" },
      { english: "He went through a difficult time", russian: "он прошёл трудный период" },
      { english: "We walked past the queue", russian: "мы прошли мимо очереди" },
      { english: "They walked through the crowd", russian: "они прошли сквозь толпу" },
      { english: "I walked past the church", russian: "я прошёл мимо церкви" },
      { english: "She went through the arch", russian: "она прошла под аркой" }
    ]
  },
  {
    prefix: "от",
    sentences: [
      { english: "I stepped away from the door (male, on foot)", russian: "я отошёл от двери" },
      { english: "I stepped away from the window (female, on foot)", russian: "я отошла от окна" },
      { english: "He walked away from the building", russian: "он отошёл от здания" },
      { english: "She walked away from the noise", russian: "она отошла от шума" },
      { english: "We moved away from the crowd", russian: "мы отошли от толпы" },
      { english: "They walked away silently", russian: "они молча отошли" },
      { english: "I drove away from the accident", russian: "я отъехал от места аварии" },
      { english: "She drove away from the house", russian: "она отъехала от дома" },
      { english: "We drove away slowly", russian: "мы медленно отъехали" },
      { english: "They drove away without a word", russian: "они отъехали, не сказав ни слова" },
      { english: "The car pulled away from the curb", russian: "машина отъехала от тротуара" },
      { english: "He walked back from the road", russian: "он отошёл от дороги" },
      { english: "She walked away from the edge", russian: "она отошла от края" },
      { english: "We moved away from the fire", russian: "мы отошли от костра" },
      { english: "The bus pulled away", russian: "автобус отъехал" },
      { english: "He stepped away to make a call", russian: "он отошёл, чтобы позвонить" },
      { english: "She stepped away for a minute", russian: "она отошла на минуту" },
      { english: "They moved away from the danger", russian: "они отошли от опасности" },
      { english: "I backed away slowly", russian: "я медленно отошёл" },
      { english: "She quietly walked away", russian: "она тихо отошла" },
      { english: "We stepped back from the argument", russian: "мы отошли от ссоры" },
      { english: "He drove away from the checkpoint", russian: "он отъехал от контрольно-пропускного пункта" }
    ]
  }
];